AC-19 send parameters
Diplomarbeit-PGHFP-2024-2025/ac-station pull request #5
Opened 2024-11-13 10:14 UTC by JonasPfeifer05

2024-11-13 10:18 UTC, leToxic requested changes, later dismissed
PropertyQueryResponse should be set in storage and not single dangling params

2024-11-13 10:18 UTC, leToxic commented on src/fetch_agent/fetch_agent/agent.py
> +    ctx.storage.set("open_time_frames", [(0, 0), (0, 0)])
imo should be in one set as JSON in pattern of PropertyResponse

2024-11-13 10:18 UTC, leToxic commented on src/fetch_agent/fetch_agent/agent.py
> +    response = PropertyQueryResponse(
here you are using the Response. Why dont just save the Object and read the object

2024-11-13 10:19 UTC, xFizzar submitted a review, later dismissed
geo point not being sent when registering station

2024-11-13 10:21 UTC, ToBinio requested changes

2024-11-13 10:21 UTC, ToBinio commented on justfile
> +    rm -rd venv/lib/python3.12/site-packages/aca_protocols-0.1.0.dist-info
works as temp fix see [ac-32](https://autocharge.atlassian.net/jira/software/projects/AC/boards/2?selectedIssue=AC-32)

2024-11-13 10:21 UTC, ToBinio commented on justfile
> +all:
wtf

2024-11-13 10:56 UTC, JonasPfeifer05 commented on justfile
> +    rm -rd venv/lib/python3.12/site-packages/aca_protocols-0.1.0.dist-info
so its ok to keep this for now?

2024-11-13 10:58 UTC, JonasPfeifer05 commented on justfile
> +all:
```suggestion
build-run-agent:
    just fix
    just build
    just run-agent
```
better?

2024-11-13 11:23 UTC, ToBinio commented on justfile
> +all:
a lot

2024-11-13 11:23 UTC, ToBinio commented on justfile
> +    rm -rd venv/lib/python3.12/site-packages/aca_protocols-0.1.0.dist-info
yes

2024-11-14 08:10 UTC, ToBinio approved these changes

2024-11-14 08:12 UTC, merged